module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/Hdf6sdiJKo48zsPHgsIbkg',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.ibb.co/XrhXt1jK/tourl-1766509613542.jpg',
    NEWSLETTER_JID: '120363423304057342@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '𝗔𝗟𝗢𝗡𝗘 𝗠𝗜𝗡𝗜',
    OWNER_NAME: 'AKARSHANA',
    OWNER_NUMBER: '94714768679',
    BOT_VERSION: '5.0.0',
    BOT_FOOTER: '> 𝙿𝙾𝚆𝙴𝚁𝙳 𝙱𝚈 𝗔𝗟𝗢𝗡𝗘 𝗠𝗜𝗡𝗜 𝙾𝙵𝙲 🫟',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbBTCb6E50Ub9aV3133f',
};
